// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrrC69sCV2KnPyC91A92ekof-W7vWG5ew',
    appId: '1:1075456429685:web:8c318265eeaa20bcb9723c',
    messagingSenderId: '1075456429685',
    projectId: 'leveling-1623e',
    authDomain: 'leveling-1623e.firebaseapp.com',
    storageBucket: 'leveling-1623e.firebasestorage.app',
    measurementId: 'G-2T4YNN24VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgiZG6V0aAFsjy84riXmkUVSjI93jZ3dU',
    appId: '1:1075456429685:android:d52dc6d26c8c2d0eb9723c',
    messagingSenderId: '1075456429685',
    projectId: 'leveling-1623e',
    storageBucket: 'leveling-1623e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDH9VyKWS1sGRet9V_ApGILR24t121vCwI',
    appId: '1:1075456429685:ios:8071b35200f08c12b9723c',
    messagingSenderId: '1075456429685',
    projectId: 'leveling-1623e',
    storageBucket: 'leveling-1623e.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDH9VyKWS1sGRet9V_ApGILR24t121vCwI',
    appId: '1:1075456429685:ios:8071b35200f08c12b9723c',
    messagingSenderId: '1075456429685',
    projectId: 'leveling-1623e',
    storageBucket: 'leveling-1623e.firebasestorage.app',
    iosBundleId: 'com.example.levelup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrrC69sCV2KnPyC91A92ekof-W7vWG5ew',
    appId: '1:1075456429685:web:9a853941060aab98b9723c',
    messagingSenderId: '1075456429685',
    projectId: 'leveling-1623e',
    authDomain: 'leveling-1623e.firebaseapp.com',
    storageBucket: 'leveling-1623e.firebasestorage.app',
    measurementId: 'G-H1G8KPGDZH',
  );
}
